webserver/config/routes.rb
Rails.application.routes.draw do
  namespace :graphium do
    resources :cities
  end
  namespace :graphium do
    
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
    

  root 'public/site#index'
  namespace :public do
      resources :site do
          collection do
            get 'version'
            get 'about'
          end
      end
  end
  namespace :graphium do
       resources :agent
       resources :street
       resources :analytics do
           collection do
              get 'getSwarmActive'
              get 'getSwarmAndAgents'
              get 'history'
              get 'finishSwarm'
          end
       end
      resources :configurations
      resources :swarm do
          collection do
              get 'launcher'
              get 'startSwarm'
          end
      end
  end
  resources :dashboard
 

    
end

webserver/app/models/graphium/agent.rb
class Graphium::Agent
    include Mongoid::Document
    field :identifier, type: String
    field :name, type: String
    field :last_lng, type: Float
    field :last_lat, type: Float
    field :last_street, type: String
    field :host, type: String
    field :swarm_identifier, type: String
    field :end_at, type: String
    field :active, type: Boolean
    field :cycles, type: Integer
    field :pathbread, type: Array
    field :color, type: String
    field :last_street_id_osm, type: Integer
    store_in collection: "agent", database: "graphium"
end

webserver/app/models/graphium/city.rb
class Graphium::City
  include Mongoid::Document
  field :name, type: String
  field :state, type: String
  field :state_code, type: String
  field :country, type: String
  field :country_code, type: String
  field :population, type: Integer
  field :osm_node_id, type: Integer
  field :city_id, type: String  
  field :lat, type: Float
  field :lng, type: Float
  store_in collection: "city", database: "graphium"
end

webserver/app/models/graphium/configuration.rb
class Graphium::Configuration
  include Mongoid::Document
    
  field :swarm_agent_number, type: Integer
  field :swarm_seconds_to_check_agents, type: Integer
  field :swarm_agent_names_API, type: String
  field :swarm_agent_names, type: Array
  field :swarm_agent_colors, type: Array
  field :mongo_db, type: String
  field :mongo_host, type: String
  field :mongo_port, type: Integer
  field :inf_positive, type: Integer
  field :inf_negative, type: Integer
  field :osmapi_user, type: String
  field :osmapi_password, type: String
    
  store_in collection: "configuration", database: "graphium"
end

webserver/app/models/graphium/street.rb
class Graphium::Street
    include Mongoid::Document
    field :name_osm, type: String
    field :type_osm, type: String
    field :surface_osm, type: String
    field :nodes, type: Array
    field :id_osm, type: Integer
    store_in collection: "street", database: "graphium"
end

webserver/app/models/graphium/swarm.rb
class Graphium::Swarm
    include Mongoid::Document
    field :name, type: String
    field :identifier, type: String
    field :city_id, type: String
    field :num_agent, type: Integer
    field :user_email, type: String
    field :active, type: Boolean
    field :host, type: String
    field :logs, type: Array
    field :cycles, type: Integer
    field :start_at, type: String
    field :end_at, type: String
    field :qmi, type: Float
    field :end_well, type: Boolean
    field :seconds_to_check_agents, type: Integer
    store_in collection: "swarm", database: "graphium"
end

webserver/app/controllers/graphium/agent_controller.rb
class Graphium::AgentController < ApplicationController
    
    layout "inside"
    before_filter :authenticate_user!
    def index
        @agents = Graphium::Agent.all#where({'active': true})
    end
end

webserver/app/controllers/graphium/analytics_controller.rb
class Graphium::AnalyticsController < ApplicationController
    respond_to :json, :html, :js
    before_filter :authenticate_user!
    layout "inside"
    def index
        
    end
    
    def getSwarmActive
        @analytics = {}
        @analytics['swarm'] = nil
        @analytics['agents'] = []
        @analytics['swarm'] = Graphium::Swarm.where(:active => true, :user_email => current_user.email).first
        if @analytics['swarm'] != nil
            @analytics['agents'] = Graphium::Agent.where(:swarm_identifier => @analytics['swarm'].identifier )
        end
        #@analytics_agent = Graphium::AgentStory.all
        respond_to do |format|
          format.json { render :json => @analytics }
        end
    end
    
    def history
        @swarms = Graphium::Swarm.where(:active => false).all
    end
    
    def getSwarmAndAgents
        @analytics = {}
        @analytics['swarm'] = nil
        @analytics['agents'] = []
        @analytics['swarm'] = Graphium::Swarm.where(:identifier => params[:swarm_identifier]).first
        if @analytics['swarm'] != nil
            @analytics['agents'] = Graphium::Agent.where(:swarm_identifier => @analytics['swarm'].identifier )
        end
        #@analytics_agent = Graphium::AgentStory.all
        respond_to do |format|
          format.json { render :json => @analytics }
        end
    end
    
    def finishSwarm
        @swarm = Graphium::Swarm.where(:identifier => params[:swarm_identifier]).first
        if @swarm
            @swarm.active = false
            if @swarm.save
                respond_to do |format|
                  format.json { render :json => true }
                end
            else
                respond_to do |format|
                  format.json { render :json => false }
                end
            end
        else
            respond_to do |format|
              format.json { render :json => false }
            end
        end
    end
end

webserver/app/controllers/graphium/cities_controller.rb
class Graphium::CitiesController < ApplicationController
  before_action :set_graphium_city, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout "inside"
  # GET /graphium/cities
  # GET /graphium/cities.json
  def index
    @graphium_cities = Graphium::City.all
  end

  # GET /graphium/cities/1
  # GET /graphium/cities/1.json
  def show
  end

  # GET /graphium/cities/new
  def new
    @graphium_city = Graphium::City.new
  end

  # GET /graphium/cities/1/edit
  def edit
  end

  # POST /graphium/cities
  # POST /graphium/cities.json
  def create
    @graphium_city = Graphium::City.new(graphium_city_params)

    respond_to do |format|
      if @graphium_city.save
        format.html { redirect_to @graphium_city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @graphium_city }
      else
        format.html { render :new }
        format.json { render json: @graphium_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graphium/cities/1
  # PATCH/PUT /graphium/cities/1.json
  def update
    respond_to do |format|
      if @graphium_city.update(graphium_city_params)
        format.html { redirect_to @graphium_city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @graphium_city }
      else
        format.html { render :edit }
        format.json { render json: @graphium_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graphium/cities/1
  # DELETE /graphium/cities/1.json
  def destroy
    @graphium_city.destroy
    respond_to do |format|
      format.html { redirect_to graphium_cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graphium_city
      @graphium_city = Graphium::City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def graphium_city_params
      params.require(:graphium_city).permit(:name, :state, :state_code, :country, :country_code, :population, :osm_node_id)
    end
end

webserver/app/controllers/graphium/configurations_controller.rb
class Graphium::ConfigurationsController < ApplicationController

  layout "inside"
  before_filter :authenticate_user!
  before_action :set_graphium_configuration, only: [:show, :edit, :update, :destroy]

  # GET /graphium/configurations
  # GET /graphium/configurations.json
  def index
    @graphium_configurations = Graphium::Configuration.all
  end

  # GET /graphium/configurations/1
  # GET /graphium/configurations/1.json
  def show
  end

  # GET /graphium/configurations/new
  def new
    @graphium_configuration = Graphium::Configuration.new
  end

  # GET /graphium/configurations/1/edit
  def edit
  end

  # POST /graphium/configurations
  # POST /graphium/configurations.json
  def create
    @graphium_configuration = Graphium::Configuration.new(graphium_configuration_params)

    respond_to do |format|
      if @graphium_configuration.save
        format.html { redirect_to @graphium_configuration, notice: 'Configuration was successfully created.' }
        format.json { render :show, status: :created, location: @graphium_configuration }
      else
        format.html { render :new }
        format.json { render json: @graphium_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graphium/configurations/1
  # PATCH/PUT /graphium/configurations/1.json
  def update
    respond_to do |format|
     
      # change format of names
      names = graphium_configuration_params[:swarm_agent_names]
      names_to_save = []
      names = names.split(',')
      names.each do |name|
          names_to_save << name
      end
      graphium_configuration_params[:swarm_agent_names] = names_to_save
      
      # change format of colors
      colors = graphium_configuration_params[:swarm_agent_colors]
      colors_to_save = []
      colors = colors.split(',')
      colors.each do |color|
          colors_to_save << color
      end
      graphium_configuration_params[:swarm_agent_colors] = colors_to_save
      logger.info 'PARAMS'
      logger.info graphium_configuration_params
        
      # updating manually
      @graphium_configuration.swarm_agent_number = graphium_configuration_params[:swarm_agent_number]
      @graphium_configuration.swarm_agent_names_API = graphium_configuration_params[:swarm_agent_names_API]
      @graphium_configuration.swarm_agent_names = names_to_save
      @graphium_configuration.mongo_db = graphium_configuration_params[:mongo_db]
      @graphium_configuration.mongo_host = graphium_configuration_params[:mongo_host]
      @graphium_configuration.mongo_port = graphium_configuration_params[:mongo_port]
      @graphium_configuration.swarm_agent_colors = colors_to_save
      @graphium_configuration.inf_positive = graphium_configuration_params[:inf_positive]
      @graphium_configuration.inf_negative = graphium_configuration_params[:inf_negative]
      @graphium_configuration.osmapi_user = graphium_configuration_params[:osmapi_user]
      @graphium_configuration.osmapi_password = graphium_configuration_params[:osmapi_password]
      @graphium_configuration.swarm_seconds_to_check_agents = graphium_configuration_params[:swarm_seconds_to_check_agents]
        
      if @graphium_configuration.save
        
        format.html { redirect_to "/graphium/configurations/1/edit", notice: 'Configuration was successfully updated.' }
        format.json { render :show, status: :ok, location: @graphium_configuration }
      else
        format.html { render :edit }
        format.json { render json: @graphium_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graphium/configurations/1
  # DELETE /graphium/configurations/1.json
  def destroy
    @graphium_configuration.destroy
    respond_to do |format|
      format.html { redirect_to graphium_configurations_url, notice: 'Configuration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graphium_configuration
        
      if Graphium::Configuration.all.length == 0
          Graphium::Configuration.create( :swarm_agent_number => 3, :swarm_agent_names_API => "http://namey.muffinlabs.com/name.json?with_surname=true&frequency=all", :swarm_agent_names =>['Coralina Malaya','Abigail Johnson','Antonietta Marinese','Elisa Rogoff','Serafim Folkerts','Dulce Barrell'], :mongo_db => "graphium",:mongo_host =>"localhost",:mongo_port =>27017, :swarm_agent_colors => ["#E91E63", "#9C27B0", "#F44336", "#673AB7", "#3F51B5", "#2196F3", "#00BCD4", "#009688", "#4CAF50", "#CDDC39", "#FF9800","#795548","#FF5722","#607D8B","#9E9E9E","#827717"],:inf_positive => 99999, :inf_negative => -99999, :osmapi_user => "glaucomunsberg",:osmapi_password => "30271255", :swarm_seconds_to_check_agents => 3, :swarm_agent_cycles_number => -1, :city_id => nil)
      end
      params[:id] = Graphium::Configuration.all.first.id
      @graphium_configuration = Graphium::Configuration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def graphium_configuration_params
      params.require(:graphium_configuration).permit(:swarm_agent_number, :swarm_seconds_to_check_agents, :swarm_agent_names_API, :swarm_agent_names, :mongo_db, :mongo_host, :mongo_port, :swarm_agent_colors, :inf_positive, :inf_negative, :osmapi_user, :osmapi_password)
    end
end

webserver/app/controllers/graphium/street_controller.rb
class Graphium::StreetController < ApplicationController
    layout "inside"
    before_filter :authenticate_user!
    def index
        @streets = Graphium::Street.where(:name_osm.nin => ["", nil]).limit(200)
    end
end

webserver/app/controllers/graphium/swarm_controller.rb
require 'net/http'

class Graphium::SwarmController < ApplicationController
    
    layout "inside"
    before_filter :authenticate_user!
    respond_to :json, :html, :js
    
    def index
        @swarms = Graphium::Swarm.all #where({'active': true})
        @swarm_actives = Graphium::Swarm.where({'active': true,'user_email': current_user.email})
    end
    
    def launcher
        @swarms = Graphium::Swarm.where({'active': true,'user_email': current_user.email})
    end
    
    def startSwarm
        
        

        name = params[:swarm_name]
        name = name.gsub(" ","_")
        
        swarm = Graphium::Swarm.new
        swarm.identifier                = params[:swarm_identifier]
        swarm.name                      = name
        swarm.user_email                = current_user.email
        swarm.active                    = true
        swarm.seconds_to_check_agents   = params[:swarm_turns].to_i
        swarm.city_id                   = params[:swarm_city]
        swarm.num_agent                 = params[:swarm_num_agent].to_i
        swarm.cycles                    = params[:swarm_agent_cycles].to_i
        swarm.logs                      = []
        swarm.start_at                  = Time.now.strftime('%Y-%m-%d %H:%M:%S')
        swarm.save
        
        locations = []
        
        if params[:swarm_wish_list]
            locations_from_params = params[:swarm_wish_list].split(':')
            locations_from_params.each do |each_location|
                lat_lng = each_location.split(',')
                if lat_lng.length == 2
                    
                    wishlist                    = Graphium::Wishlist.new
                    wishlist.lat                = lat_lng[0].to_f
                    wishlist.lng                = lat_lng[1].to_f
                    wishlist.swarm_identifier   = swarm.identifier
                    wishlist.user_email         = current_user.email
                    wishlist.dt_required        = Time.now.strftime('%Y-%m-%d %H:%M:%S')
                    wishlist.processed          = false
                    wishlist.city_id            = params[:swarm_city]
                    wishlist.priority           = 1.0
                    
                    url = URI.parse("http://nominatim.openstreetmap.org/reverse?&format=json&lat=#{lat_lng[0]}&lon=#{lat_lng[1]}")
                    req = Net::HTTP::Get.new(url.to_s)
                    res = Net::HTTP.start(url.host, url.port) {|http|
                      http.request(req)
                    }
                    logger.info 'API NOMINATIM'
                    logger.info "http://nominatim.openstreetmap.org/reverse?&format=json&lat=#{lat_lng[0]}&lon=#{lat_lng[1]}"
                    json_result = JSON.parse(res.body) 
                    if json_result.key?("osm_id")
                        wishlist.osm_way_id = json_result['osm_id'].to_i
                        if json_result.key?("address") and json_result['address'].key?("road")
                            wishlist.address = json_result['address']['road']
                        end
                        
                    end
                    
                    wishlist.save
                    
                end
            end
        end
        logger.info 'Inicialize the swarm'
        Thread.new do
            logger.info 'Start thread'
            logger.info system( "python ../swarm/Main.py -i #{params[:swarm_identifier]}" )
        end
        @output = true
        respond_to do |format|
          format.json { render :json => {"output" => @output} }
        end
    end
end

webserver/app/views/graphium/configurations/_form.html.erb
<%= form_for(@graphium_configuration) do |f| %>
  <% if @graphium_configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@graphium_configuration.errors.count, "error") %> prohibited this graphium_configuration from being saved:</h2>
      <ul>
      <% @graphium_configuration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
      <h4>Agent params</h4>
  </div>
  <div class="row">
      <div class="field col s6">
        <%= f.label :swarm_agent_number %><br>
        <%= f.number_field :swarm_agent_number %>
      </div>
      <div class="field col s6">
        <%= f.label :swarm_seconds_to_check_agents %><br>
        <%= f.number_field :swarm_seconds_to_check_agents %>
      </div>
  </div>
  
  <div class="field">
    <%= f.label :swarm_agent_names_API %><br>
    <%= f.text_field :swarm_agent_names_API %>
  </div>
  <div class='field'>
      <label for="names">Agents' names</label>
      <div id='names' class="chips chips-names"></div>
  </div>
  <div class="field"  style="display:none">
    <%= f.label :swarm_agent_names %><br>
    <%= f.text_field :swarm_agent_names %>
  </div>
  <div class='field'>
      <label for="colors">Agents' colors</label>
      <div id='colors' class="chips chips-colors"></div>
  </div>
  <div class="field" style="display:none">
    <%= f.label :swarm_agent_colors %><br>
    <%= f.text_field :swarm_agent_colors %>
  </div>
  <div class='row'>
      <h4>MongoDB connection</h4>
  </div>
  <div class='row'>
      <div class="field col s4">
        <%= f.label :mongo_db %><br>
        <%= f.text_field :mongo_db %>
      </div>
      <div class="field col s4">
        <%= f.label :mongo_host %><br>
        <%= f.text_field :mongo_host %>
      </div>
      <div class="field col s4">
        <%= f.label :mongo_port %><br>
        <%= f.number_field :mongo_port %>
      </div>
  </div>
  <div class='row'>
      <h4>Open Street Map API </h4>
  </div>
  <div class='row'>
      <div class="field col s6">
        <%= f.label :osmapi_password %><br>
        <%= f.text_field :osmapi_password %>
      </div>
      <div class="field  col s6">
        <%= f.label :osmapi_user %><br>
        <%= f.text_field :osmapi_user %>
      </div>
  </div>
  <div class='row'>
      <h4>General</h4>
  </div>
  <div class='row'>
      <div class="field col s6">
        <%= f.label :inf_positive %><br>
        <%= f.number_field :inf_positive %>
      </div>
      <div class="field col s6">
        <%= f.label :inf_negative %><br>
        <%= f.number_field :inf_negative %>
      </div>
  </div>
  <div class="actions">
    <%=form_save_btn f.submit %>
  </div>
<% end %>
<script>
    var data_names = [];
    <%  
        names = ""
        @graphium_configuration.swarm_agent_names.each do |name|
            %>
                data_names.push({tag: '<%=name%>'})
            <%
            names += name+","
        end
        if names != ""
            names = names[0...names.length-1]
        end
    %>
    $('#graphium_configuration_swarm_agent_names').val('<%=names%>')
    
    $('.chips-names').material_chip({
        data: data_names,
        secondaryPlaceholder: '+Names',
    });
    
    $('.chips-names').on('chip.add', function(e, chip){
        $('#graphium_configuration_swarm_agent_names').val('');
        console.log('adding',$('.chips-names').material_chip('data'))
        names = ""
        namesArray = $('.chips-names').material_chip('data')
        for(var a=0; a < namesArray.length;a++){
            names += namesArray[a].tag+","
        }
        if(names!=""){
            names = names.substring(0,names.length-1)
        }
        $('#graphium_configuration_swarm_agent_names').val(names);
    });

    $('.chips-names').on('chip.delete', function(e, chip){
        $('#graphium_configuration_swarm_agent_names').val('');
        console.log('adding',$('.chips-names').material_chip('data'))
        names = ""
        namesArray = $('.chips-names').material_chip('data')
        for(var a=0; a < namesArray.length;a++){
            names += namesArray[a].tag+","
        }
        if(names!=""){
            names = names.substring(0,names.length-1)
        }
        $('#graphium_configuration_swarm_agent_names').val(names);
    });
    
    
    var data_colors = [];
    <%  
        colors = ""
        @graphium_configuration.swarm_agent_colors.each do |color|
            %>
                data_colors.push({tag: '<%=color%>'})
            <%
            colors += color+","
        end
        if colors != ""
            colors = colors[0...colors.length-1]
        end
    %>
    $('#graphium_configuration_swarm_agent_colors').val('<%=colors%>')
    
    $('.chips-colors').material_chip({
        data: data_colors,
        secondaryPlaceholder: '+Colors',
    });
    
    $('.chips-colors').on('chip.add', function(e, chip){
        $('#graphium_configuration_swarm_agent_colors').val('');
        //console.log('adding',$('.chips-names').material_chip('data'))
        colors = ""
        colorsArray = $('.chips-names').material_chip('data')
        for(var a=0; a < colorsArray.length;a++){
            colors += colorsArray[a].tag+","
        }
        if(colors!=""){
            colors = colors.substring(0,colors.length-1)
        }
        $('#graphium_configuration_swarm_agent_colors').val(colors);
    });

    $('.chips-names').on('chip.delete', function(e, chip){
        $('#graphium_configuration_swarm_agent_colors').val('');
        //console.log('adding',$('.chips-names').material_chip('data'))
        colors = ""
        colorsArray = $('.chips-names').material_chip('data')
        for(var a=0; a < colorsArray.length;a++){
            colors += colorsArray[a].tag+","
        }
        if(colors!=""){
            colors = colors.substring(0,colors.length-1)
        }
        $('#graphium_configuration_swarm_agent_colors').val(colors);
    });
    
    
    
</script>

webserver/app/views/graphium/configurations/edit.html.erb
<%=breadcrumbs [{:name => 'Home',:path => '/'},{:name => 'Configuration', :path => '/graphium/configurations'}], 'Default', true%>

<%= render 'form' %>

webserver/app/views/graphium/configurations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Graphium Configurations</h1>

<table>
  <thead>
    <tr>
      <th>Swarm agent number</th>
      <th>Swarm agent names api</th>
      <th>Swarm agent names</th>
      <th>Mongo db</th>
      <th>Mongo host</th>
      <th>Mongo port</th>
      <th>Colors</th>
      <th>Inf positive</th>
      <th>Inf negative</th>
      <th>Osmapi user</th>
      <th>Osmapi password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @graphium_configurations.each do |graphium_configuration| %>
      <tr>
        <td><%= graphium_configuration.swarm_agent_number %></td>
        <td><%= graphium_configuration.swarm_agent_names_API %></td>
        <td><%= graphium_configuration.swarm_agent_names %></td>
        <td><%= graphium_configuration.mongo_db %></td>
        <td><%= graphium_configuration.mongo_host %></td>
        <td><%= graphium_configuration.mongo_port %></td>
        <td><%= graphium_configuration.colors %></td>
        <td><%= graphium_configuration.inf_positive %></td>
        <td><%= graphium_configuration.inf_negative %></td>
        <td><%= graphium_configuration.osmapi_user %></td>
        <td><%= graphium_configuration.osmapi_password %></td>
        <td><%= link_to 'Show', graphium_configuration %></td>
        <td><%= link_to 'Edit', edit_graphium_configuration_path(graphium_configuration) %></td>
        <td><%= link_to 'Destroy', graphium_configuration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Configuration', new_graphium_configuration_path %>

webserver/app/views/graphium/configurations/new.html.erb
<h1>New Graphium Configuration</h1>

<%= render 'form' %>

<%= link_to 'Back', graphium_configurations_path %>

webserver/app/views/graphium/configurations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Swarm agent number:</strong>
  <%= @graphium_configuration.swarm_agent_number %>
</p>

<p>
  <strong>Swarm agent names api:</strong>
  <%= @graphium_configuration.swarm_agent_names_API %>
</p>

<p>
  <strong>Swarm agent names:</strong>
  <%= @graphium_configuration.swarm_agent_names %>
</p>

<p>
  <strong>Mongo db:</strong>
  <%= @graphium_configuration.mongo_db %>
</p>

<p>
  <strong>Mongo host:</strong>
  <%= @graphium_configuration.mongo_host %>
</p>

<p>
  <strong>Mongo port:</strong>
  <%= @graphium_configuration.mongo_port %>
</p>

<p>
  <strong>Colors:</strong>
  <%= @graphium_configuration.colors %>
</p>

<p>
  <strong>Inf positive:</strong>
  <%= @graphium_configuration.inf_positive %>
</p>

<p>
  <strong>Inf negative:</strong>
  <%= @graphium_configuration.inf_negative %>
</p>

<p>
  <strong>Osmapi user:</strong>
  <%= @graphium_configuration.osmapi_user %>
</p>

<p>
  <strong>Osmapi password:</strong>
  <%= @graphium_configuration.osmapi_password %>
</p>

<%= link_to 'Edit', edit_graphium_configuration_path(@graphium_configuration) %> |
<%= link_to 'Back', graphium_configurations_path %>